version: '3'
services:
  node_app:
    container_name: node_app
    build: ./nodeApp
    volumes:
      - './nodeApp:/app'
    # command: bash -c /app/nodeApp/bin/start.sh
    expose:
      - '80'
    
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/config/:/etc/nginx/conf.d
