version: '3'
services:
  django:
    context: DjangoApp
    expose: 
      - '443'
    command: bash -c "cd /app && python manage.py migrate && daphne -e ssl:443:privateKey=certs/private-key.key:certKey=certs/certificate.crt app_name.asgi:application"
    volumes:
      - static_volume:/path_to_static_files
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_volume:/path_to_static_files
    depends_on:
      - django
volumes:
  - static_volume
