version: '3'
services:
  node_app:
    container_name: node_app
    build: ./nodeApp
    volumes:
      - './nodeApp:/app'
    # command: bash -c /app/nodeApp/bin/start.sh
    depends_on:
      - mongo
    
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/config/:/etc/nginx/conf.d
    depends_on:
      - mongo
      - node_app
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass