version: '3'
services:
  django:
    image: python:alpine
    expose: 
      - '80'
      # - '443'
    command: sh /app/DjangoApp/preload.sh
    volumes:
      - ./DjangoApp:/app/DjangoApp
      - static_volume:/app/DjangoApp/static/
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      # - '443:443'
    volumes:
        - ./nginx/config/:/etc/nginx/conf.d
        - static_volume:/app/DjangoApp/static/  
    depends_on:
      - django
volumes:
  static_volume: