version: '3'
services:
  django:
    build: 'DjangoApp'
    expose: 
      - '80'
      # - '443'
    # command:
    # volumes:
      # - static_volume:/path_to_static_files
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      # - '443:443'
    volumes:
        - ./nginx/config/:/etc/nginx/conf.d  
    # volumes:
      # - static_volume:/path_to_static_files
    depends_on:
      - django
# volumes:
#   static_volume: